'use client'
import { useMemo, useState } from 'react'
import { units } from '@/lib/units'
import { generateWorksheet } from '@/lib/generator'
import { Difficulty, RequestData, Subject, Volume, Worksheet } from '@/lib/types'

const purposes=['復習','苦手克服','先取り','お盆休みの宿題','計算練習','語彙・漢字練習','読解練習']
function Choice<T extends string>({items,value,onChange}:{items:T[];value:T;onChange:(v:T)=>void}){return <div className="choices">{items.map(x=><button type="button" onClick={()=>onChange(x)} className={`choice ${value===x?'selected':''}`} key={x}>{x}</button>)}</div>}
export function WorksheetMaker(){
const [grade,setGrade]=useState(4); const [subject,setSubject]=useState<Subject>('算数'); const [difficulty,setDifficulty]=useState<Difficulty>('標準'); const [volume,setVolume]=useState<Volume>('普通'); const [purpose,setPurpose]=useState('復習'); const [selected,setSelected]=useState<string[]>([]); const [notes,setNotes]=useState(''); const [worksheet,setWorksheet]=useState<Worksheet|null>(null); const [error,setError]=useState('')
const currentUnits=useMemo(()=>units.filter(u=>u.grade===grade&&u.subject===subject),[grade,subject]); const canAdvance=purpose==='先取り'
function changeGrade(value:number){setGrade(value);setSelected([]);setWorksheet(null)} function changeSubject(value:Subject){setSubject(value);setSelected([]);setWorksheet(null)}
function toggleUnit(name:string,allowed:boolean){if(!allowed)return;setSelected(s=>s.includes(name)?s.filter(x=>x!==name):[...s,name])}
function create(){if(!selected.length){setError('単元を1つ以上選んでください。');return} setError(''); const req:RequestData={id:crypto.randomUUID(),createdAt:new Date().toISOString(),grade,subject,difficulty,volume,purpose,selectedUnits:selected,notes}; const made=generateWorksheet(req); setWorksheet(made); const existing=JSON.parse(localStorage.getItem('obon-requests')||'[]'); localStorage.setItem('obon-requests',JSON.stringify([{...req,status:'generated',worksheet:made},...existing])); setTimeout(()=>document.getElementById('preview')?.scrollIntoView({behavior:'smooth'}),50)}
return <><header className="topbar"><div className="topinner"><a className="brand" href="/">お盆休み 宿題プリントメーカー</a><a className="navlink" href="/admin/login">管理者ログイン</a></div></header><main className="shell"><section className="hero"><div className="eyebrow">小学生の家庭学習を、もっと気軽に</div><h1>お子さまに合った<br/>夏休みプリントをつくる</h1><p>学年・科目・単元を選ぶだけ。お盆休みまでに学習した範囲を中心に、印刷してすぐ使える問題プリントを作成します。</p></section><section className="card"><div className="steps"><span className="step active">1. 条件を選ぶ</span><span className="step">2. プリントを確認</span><span className="step">3. 印刷・PDF保存</span></div><div className="section"><h2>学年と科目</h2><p className="hint">お子さまの学年と、取り組む科目を選んでください。</p><div className="grid"><div><label className="label">学年</label><select className="field" value={grade} onChange={e=>changeGrade(+e.target.value)}>{[1,2,3,4,5,6].map(x=><option key={x} value={x}>小学{x}年</option>)}</select></div><div><label className="label">科目</label><Choice items={['算数','国語'] as Subject[]} value={subject} onChange={changeSubject}/></div></div></div><div className="section"><h2>学習の希望</h2><p className="hint">むずかしさ・分量・目的をお選びください。</p><div className="grid"><div><label className="label">難易度</label><Choice items={['やさしい','標準','難しい'] as Difficulty[]} value={difficulty} onChange={setDifficulty}/></div><div><label className="label">分量</label><Choice items={['少なめ','普通','多め'] as Volume[]} value={volume} onChange={setVolume}/></div></div><div style={{marginTop:16}}><label className="label">目的</label><Choice items={purposes} value={purpose} onChange={setPurpose}/></div></div><div className="section"><h2>単元を選ぶ <span style={{fontSize:13,fontWeight:400,color:'#64748b'}}>（複数選択可）</span></h2><p className="hint">通常はお盆時点までの学習範囲を表示しています。{canAdvance?'先取りを選択中のため、未習の単元も選べます。':'「先取り」を選ぶと、9月以降の内容も選択できます。'}</p><div className="choices">{currentUnits.map(u=>{const allowed=u.availableByObon||canAdvance;return <button type="button" className={`choice unit ${selected.includes(u.name)?'selected':''} ${!allowed?'locked':''}`} onClick={()=>toggleUnit(u.name,allowed)} key={u.id}><b>{selected.includes(u.name)?'✓ ':''}{u.name}</b><small>{allowed?'お盆までに出題可能':`9月以降の内容${canAdvance?'（先取り）':'（先取りで選択可）'}`}</small></button>})}</div></div><div className="section"><label className="label">備考（任意）</label><textarea className="field" rows={3} value={notes} onChange={e=>setNotes(e.target.value)} placeholder="例：計算ミスが多い、短時間で終わる量がよい"></textarea><p className="footerNote">個人情報保護のため、生徒名・電話番号・住所・学校名などは入力しないでください。</p></div>{error&&<p className="error">{error}</p>}<button className="primary" onClick={create}>プリントを作成する →</button></section>{worksheet&&<Preview worksheet={worksheet} grade={grade} subject={subject} onBack={()=>setWorksheet(null)}/>}</main></> }
function Preview({worksheet,grade,subject,onBack}:{worksheet:Worksheet;grade:number;subject:Subject;onBack:()=>void}){return <section id="preview"><div className="previewHead noPrint"><div><div className="eyebrow">プレビュー</div><h1>プリントができました</h1><p className="hint">内容を確認したら、印刷画面から「PDFに保存」を選べます。</p></div><div className="actions"><button className="secondary" onClick={onBack}>条件を変更</button><button className="primary" onClick={()=>window.print()}>印刷 / PDF保存</button></div></div><article className="paper"><div className="paperTitle"><h2>{worksheet.title}</h2><div>{worksheet.summary}</div></div><div className="paperMeta"><span>なまえ：＿＿＿＿＿＿＿＿＿＿</span><span>日づけ：＿＿年＿＿月＿＿日</span></div>{worksheet.passage&&<><h3>【文章を読んで答えましょう】</h3><p style={{lineHeight:2,padding:'12px',background:'#f8fbfe'}}>{worksheet.passage}</p></>}{worksheet.problems.map((p,i)=><div className="problem" key={i}><b>問題 {i+1}.</b> {p.question}<div className="answerline"/></div>)}<div style={{pageBreakBefore:'always',paddingTop:30}}><h2 className="paperTitle">解答</h2>{worksheet.problems.map((p,i)=><div className="problem" key={i}><b>{i+1}.</b> {p.answer}{p.explanation&&<small style={{display:'block',color:'#5a7190'}}>{p.explanation}</small>}</div>)}</div></article></section>}
